import type { SiteManifest } from '$lib/types/media';
import manifest from './media.json';

/** Generated by scripts/sync-photos.mjs — run `npm run sync:photos` to refresh */
export const media = manifest as SiteManifest;
